--use master
--DROP DATABASE College

--CREATE DATABASE College
--USE College


CREATE TABLE [Role]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(30) NOT NULL
);

CREATE TABLE [EmployeeCategory]
(
	[Id] INT  PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE [Gender]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(20) NOT NULL
);

CREATE TABLE [TranscriptCategory]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(200) NOT NULL
);

CREATE TABLE [Specialty]
(
	[Code] NVARCHAR(20) PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(250) NOT NULL
);

CREATE TABLE [Group]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[Number] SMALLINT NOT NULL,
	[SpecialtyCode] NVARCHAR(20) FOREIGN KEY REFERENCES [Specialty](Code)
);

CREATE TABLE [Employee]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[LastName] NVARCHAR(254) NOT NULL,
	[FirstName] NVARCHAR(254) NOT NULL,
	[MiddleName] NVARCHAR(254) NOT NULL,
	[Login] NVARCHAR(32) NOT NULL,
	[Password] NVARCHAR(32) NOT NULL,
	[IsFired] BIT NULL,
	[CategoryId] INT FOREIGN KEY REFERENCES [EmployeeCategory]([Id]) NOT NULL,
	[RoleId] INT FOREIGN KEY REFERENCES [Role]([Id]) NOT NULL,
);

CREATE TABLE [Student]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[LastName] NVARCHAR(254) NOT NULL,
	[FirstName] NVARCHAR(254) NOT NULL,
	[MiddleName] NVARCHAR(254) NULL,
	[BirthDate] DATE NULL,
	[Email] NVARCHAR(254) NULL,
	[Phone] NVARCHAR(25) NULL,
	[Login] NVARCHAR(32) NOT NULL,
	[Password] NVARCHAR(32) NULL,
	[Adrress] NVARCHAR(254) NULL,
	[GenderId] INT FOREIGN KEY REFERENCES [Gender]([Id]) NOT NULL,
	[GroupId] INT FOREIGN KEY REFERENCES [Group]([Id]) NOT NULL,
	[IsExpelled] BIT,
	[Photo] VARBINARY(MAX) NULL
)

CREATE TABLE [Semester]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[Name] INT NOT NULL
);

CREATE TABLE [Subject]
(
	[Code] NVARCHAR(20) PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(500) NOT NULL,
	[TotalHours] SMALLINT NOT NULL,
	[UDMDK] SMALLINT NULL,
	[LabPract] SMALLINT NULL,
	[CourseWork] SMALLINT NULL,
	[Practice] SMALLINT NULL,
	[IndependentWork] NVARCHAR(10) NULL,
	[SemesterId] INT FOREIGN KEY REFERENCES [Semester]([Id]) NULL
);

CREATE TABLE [Transcript]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[CategoryId] INT FOREIGN KEY REFERENCES [TranscriptCategory]([Id]) NOT NULL,
	[SubjectCode] NVARCHAR(20) FOREIGN KEY REFERENCES [Subject]([Code]) NOT NULL,
	[GroupId] INT FOREIGN KEY REFERENCES [Group]([Id]) NOT NULL,
	[SpecialId] NVARCHAR(20) FOREIGN KEY REFERENCES [Specialty]([Code]) NOT NULL,
	[EmployeeId] INT FOREIGN KEY REFERENCES [Employee]([Id]) NOT NULL,
	[NumberOfHours] SMALLINT NOT NULL,
	[Date] DATE NOT NULL
);

CREATE TABLE [Mark]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[TranscriptId] INT FOREIGN KEY REFERENCES [Transcript]([Id]) NOT NULL,
	[StudentId] INT FOREIGN KEY REFERENCES [Student]([Id]) NOT NULL,
	[Written] SMALLINT NULL,
	[Verbal] SMALLINT NULL,
	[Overall] SMALLINT NOT NULL,
);
